apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-deployment
  labels:
    app: color
spec:
  replicas: 3
  selector:
    matchLabels:
      app: color
  template:
    metadata:
      labels:
        app: color
    spec:
      containers:
        - name: color
          image: adah001/color-app:19006649578
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: color
spec:
  type: LoadBalancer
  selector:
    app: color
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
