apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-deployment
  labels:
    app: color
spec:
  replicas: 3
  selector:
    matchLabels:
      app: color
  template:
    metadata:
      labels:
        app: color
    spec:
      containers:
      - name: color
        image: adah001/color-app:19006649578
        ports:
        - containerPort: 3000
